version: '3.9'
services:
  rabbitmq-man:
    image: rabbitmq:3.12.4-management
    container_name: rabbitmq-management
    ports:
      - 15672:15672
    # volumes:
    #   - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
  rabbitmq:
    image: rabbitmq:3.12.4
    container_name: rabbitmq
    ports:
      - 5673:5672
    # volumes:
    #   - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=dev
      - RABBITMQ_DEFAULT_PASS=dev
